### PR TITLE
added enc_type argument to http_build_query

### PR DESCRIPTION
**Pull request by therightstuff**
(enc_type required for OAuth signature encoding), minor whitespace fix in rawurlencode

### CODE REVIEW

**Comment by kvz** [comment]
Great contribution, thanks! One minor thing, the depends on syntax only supports one dependency per line. If you can just fix that this is ready to merge afaic :+1:

**Comment by therightstuff** [comment]
Is the build failure expected?

**Comment by therightstuff** [comment]
I apologize for the failed commit...

**Comment by therightstuff** [comment]
The test is passing locally but not with the automated build, any suggestions?

**Comment by kvz** [comment]
Here's the fail:

```
ERROR: --> http_build_query#3 failed. 
ERROR: expected: 
"myvar_0=foo&myvar_1=bar&myvar_2=baz&myvar_3=boom&php=hypertext%20processor&cow=milk"
returned: 
"myvar_0=foo2myvar_1=bar2myvar_2=baz2myvar_3=boom2php=hypertext+processor2cow=milk"

```

**Comment by therightstuff** [comment]
Hi there

I've tried all sorts of things, as you have probably seen I even started from scratch thinking that I finally had it down and not wanting to pollute the commits. I've completely cleaned up my dev environment and I'd like to get this done as soon as possible, but when I run "make test" on the latest revision of kvz/phpjs (without any modifications) the test fails as follows:

image

Any ideas? I assume that as soon as the test works I'll be able to figure out what's wrong with my changes and fix them accordingly...

**Comment by kvz** [comment]
Odd. `array_count_values` failed for me too, was listed in `known_failures.txt` so not fatally.

Whatever the reason this crashed for you and not here or on Tavis, I fixed a problem here: https://github.com/kvz/phpjs/commit/c8080077f2ba15a636dfc36b468e0ff879448023

Hope this helps

**Comment by therightstuff** [comment]
Thanks for fixing that! The tests are working now. After much debugging, however, I've discovered that the problem lies with having two "depends on" lines in the comments - the second line is simply ignored. Do you have an example of how to resolve this?

**Comment by therightstuff** [comment]
Hi again - I'm not familiar with the comment requirements and I'd like to complete this as soon as possible. Is there any documentation available?

**Comment by kvz** [comment]
Hi, I just had a minute to verify dependency parsing works and wrote a test for it. All seems good.

**Comment by kvz** [comment]
It appears though you've added legacy style prefixes `-` `*` etc to the comment header keys. Can you try removing those?

**Comment by kvz** [comment]
Maybe you can try rebasing your changes upon master? There may be more fixes since your fork.

**Comment by therightstuff** [comment]
Hi

I don't know what's different between my environment and yours, but I've rebased and the second "depends on" comment is consistently ignored so the tests continue to fail. I added basic debug logging.

When the order is as follows, example 1 passes and the other two fail:
  //  depends on: rawurlencode
  //  depends on: urlencode
  //  example 1: http_build_query({'php': 'hypertext processor', baz: 'boom', cow: 'milk'}, '', null, 2);
  //  returns 1: 'php=hypertext%20processor&baz=boom&cow=milk'
  
DEBUG: --> strnatcmp#3 passed.
DEBUG: --> strnatcmp#4 passed.
DEBUG: --> strnatcmp#5 passed.
ERROR: 508 passed / 3 failed  / 29 known / 17 skipped
undefined:217
            console.log(urlencode(key) + '=' + urlencode(val));
                   ^
ReferenceError: urlencode is not defined
    at _http_build_query_helper (eval at <anonymous> (/home/vagrant/phpjs/lib/phpjsutil.js:266:10), <anonymous>:217:20)
    at http_build_query (eval at <anonymous> (/home/vagrant/phpjs/lib/phpjsutil.js:266:10), <anonymous>:239:17)
    at eval (eval at <anonymous> (/home/vagrant/phpjs/lib/phpjsutil.js:290:65), <anonymous>:1:15)
    at /home/vagrant/phpjs/lib/phpjsutil.js:290:11
    at /home/vagrant/phpjs/lib/phpjsutil.js:184:16
    at /home/vagrant/phpjs/lib/phpjsutil.js:202:14
    at /home/vagrant/phpjs/lib/phpjsutil.js:151:5
    at PhpjsUtil._loadDependencies (/home/vagrant/phpjs/lib/phpjsutil.js:108:7)
    at PhpjsUtil.parse (/home/vagrant/phpjs/lib/phpjsutil.js:143:8)
    at /home/vagrant/phpjs/lib/phpjsutil.js:197:10
make: *** [test] Error 1

When the order is as follows, the test fails. These results are consistent when I reorder the examples.
  //  depends on: urlencode
  //  depends on: rawurlencode

undefined:217
            console.log(rawurlencode(key) + '=' + rawurlencode(val));
                   ^
ReferenceError: rawurlencode is not defined
    at _http_build_query_helper (eval at <anonymous> (/home/vagrant/phpjs/lib/phpjsutil.js:266:10), <anonymous>:217:20)
    at http_build_query (eval at <anonymous> (/home/vagrant/phpjs/lib/phpjsutil.js:266:10), <anonymous>:243:17)
    at eval (eval at <anonymous> (/home/vagrant/phpjs/lib/phpjsutil.js:290:65), <anonymous>:1:15)
    at /home/vagrant/phpjs/lib/phpjsutil.js:290:11
    at /home/vagrant/phpjs/lib/phpjsutil.js:184:16
    at /home/vagrant/phpjs/lib/phpjsutil.js:202:14
    at /home/vagrant/phpjs/lib/phpjsutil.js:151:5
    at PhpjsUtil._loadDependencies (/home/vagrant/phpjs/lib/phpjsutil.js:108:7)
    at PhpjsUtil.parse (/home/vagrant/phpjs/lib/phpjsutil.js:143:8)
    at /home/vagrant/phpjs/lib/phpjsutil.js:197:10

**Pull request closed without merging**
