### PR TITLE
strtotime: make sure to parse ISO 8601 time strings

### LINKED ISSUE #222: strtotime works differently in different browsers
`strtotime('2015-04-15T20:33:59+02:00');`
returns `1429122839` in Chrome and `false` in the rest browsers.

The reason is that the function converts the date string to lower case but browsers (except Chrome) can't parse such strings.
So `Date.parse('2015-04-15t20:33:59+02:00')` is `NaN` in non-Chrome browsers.

I am going to fix it.

Thanks @plepe for catching this bug.

### PR DESCRIPTION
**Pull request by plepe**
fixes #222

### CODE REVIEW

**Comment by scottchiefbaker** [comment]
I haven't had time to test this yet, but it's a much needed feature.

I vote +1

**Comment by kvz** [comment]
Thank! Two things - this needs a failing test case that passes with this change. Also needs to comply with coding standards before we can consider merging.

**Comment by plepe** [comment]
I added some test cases which fail in Firefox. They do not fail in Chrome and nodejs, as V8 is much more liberal with the `Date.parse()` input.

I tried to follow the coding standards ... where did I fail?

**Comment by kvz** [comment]
Great, thank you. About the CS, 2 out of 4 added if statements aren't followed by `{}` enclosed code blocks. Our CS make them mandatory.

**Comment by plepe** [comment]
Oh yes, I missed those. Sorry.

Just updated the pull request.

**Comment by kvz** [comment]
Great! Thanks you so much <3

**Comment by evgenius** [comment]
Thank you @plepe!

**Pull request merged**
