### PR TITLE
fixed jshint detected errors

### PR DESCRIPTION
**Pull request by Codestar**
I fixed some jshint detected error for improve it :+1:

### CODE REVIEW

**Comment by kvz** [comment]
Thanks, but it seems you also removed the `type` declaration that was recently added. Could you rebase?

Also, i'm not sure if we should remove the fallthrough. I believe was added for clarity..

**Comment by Codestar** [comment]
Hi,
Yes right, i removed because i was missed ```type``` defined already. I mean here https://github.com/kvz/phpjs/blob/master/functions/var/serialize.js#L70-L71 i  was missed this comma. :smiley: i fixed it and improve for jshint.

About ```undefined``` also meaning ```default``` why we need it ?

```javascript
case 'undefined':
defaut:
````

this is same thing, no different.

```javascript
defaut:
````

Ops, maybe you mean this ?

```javascript
case 'undefined':
  // Fall-through
  break; // i can add this and commit again?
defaut:
````

**Comment by Codestar** [comment]
Oh ok, i will not touch Fall-through :smile:

**Comment by kvz** [comment]
Thanks!

**Pull request merged**
